const { add, name, sub, mult, divi } = require("./oper");
const { divide, multiple } = require("./pratice");
// const fs = require("fs");
// const sub = require("./oper");
// const name = require("./oper");
// console.log(oper);
console.log(name);
console.log(add(5, 5));
console.log(sub(15, 5));
console.log(mult(2, 7));
console.log(divi(100, 2));
console.log(divide(1000, 2500));

console.log(multiple(2, 3, 1));
console.log(multiple(2, 3, 3));
const { add, name, sub, mult, divi } = require("./oper");
const { divide, multiple } = require("./pratice");
// const fs = require("fs");
// const sub = require("./oper");
// const name = require("./oper");
// console.log(oper);
console.log(name);
console.log(add(5, 5));
console.log(sub(15, 5));
console.log(mult(2, 7));
console.log(divi(100, 2));
console.log(divide(1000, 2500));

console.log(multiple(2, 3, 1));
console.log(multiple(2, 3, 3));
const { add, name, sub, mult, divi } = require("./oper");
const { divide, multiple } = require("./pratice");
// const fs = require("fs");
// const sub = require("./oper");
// const name = require("./oper");
// console.log(oper);
console.log(name);
console.log(add(5, 5));
console.log(sub(15, 5));
console.log(mult(2, 7));
console.log(divi(100, 2));
console.log(divide(1000, 2500));

console.log(multiple(2, 3, 1));
console.log(multiple(2, 3, 3));
