const oper = require("./oper");
const oper1 = require("./pratice");
// const fs = require("fs");
// const sub = require("./oper");
// const name = require("./oper");
console.log(oper);
console.log(oper.name);
console.log(oper.add(5, 5));
console.log(oper.sub(15, 5));
console.log(oper.mult(2, 7));
console.log(oper.divi(100, 2));
console.log(oper1.divide(1000, 2500));
console.log(oper);
console.log(oper.name);
console.log(oper.add(5, 5));
console.log(oper.sub(15, 5));
console.log(oper.mult(2, 7));
console.log(oper.divi(100, 2));
console.log(oper1.divide(1000, 2500));
console.log(oper);
console.log(oper.name);
console.log(oper.add(5, 5));
console.log(oper.sub(15, 5));
console.log(oper.mult(2, 7));
console.log(oper.divi(100, 2));
console.log(oper1.divide(1000, 2500));
